# SPDX-FileCopyrightText: 2025 Space Kobold Games and Contributors <https://github.com/space-kobold/alpha-paradox>
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
    "rsi-schema.json",
]
SPDX-FileCopyrightText = "2017-2025 Space Wizards Federation and Contributors <https://github.com/space-wizards/space-station-14>"
SPDX-License-Identifier = "LicenseRef-MIT-SpaceWizards"

[[annotations]]
path = [
    "PULL_REQUEST_TEMPLATE.md"
]
SPDX-FileCopyrightText = "2017-2025 Space Wizards Federation and Contributors <https://github.com/space-wizards/space-station-14>"
SPDX-License-Identifier = "CC-BY-SA-3.0"
