# SPDX-FileCopyrightText: 2017-2025 Space Wizards Federation and Contributors <https://github.com/space-wizards/space-station-14>
#
# SPDX-License-Identifier: LicenseRef-MIT-SpaceWizards

status = [ 
  "Build & Test Debug",
  "Build & Test Release",
  "Test Packaging",
  "YAML Linter",
  "YAML RGA schema validator",
  "YAML map schema validator",
  "Validate RSIs",
]
timeout_sec = 1800 # 30 minutes
use_squash_merge = true # Shame this can't use GH squash but what can you do
