#!/bin/bash

# SPDX-FileCopyrightText: 2017-2025 Space Wizards Federation and Contributors <https://github.com/space-wizards/space-station-14>
#
# SPDX-License-Identifier: LicenseRef-MIT-SpaceWizards

gitroot=`git rev-parse --show-toplevel`

cd "$gitroot/BuildChecker"

if [[ `uname` == MINGW* || `uname` == CYGWIN* ]]; then
    # Windows
    py -3 git_helper.py --quiet
else
    # Not Windows, so probably some other Unix thing.
    python3 git_helper.py --quiet
fi
