// SPDX-FileCopyrightText: 2017-2025 Space Wizards Federation and Contributors <https://github.com/space-wizards/space-station-14>
//
// SPDX-License-Identifier: LicenseRef-MIT-SpaceWizards

namespace Content.Shared.Procedural.Distance;

/// <summary>
/// Used if you want to limit the distance noise is generated by some arbitrary config
/// </summary>
[ImplicitDataDefinitionForInheritors]
public partial interface IDunGenDistance
{
    /// <summary>
    /// How much to blend between the original noise value and the adjusted one.
    /// </summary>
    float BlendWeight { get; }
}

