# SPDX-FileCopyrightText: 2025 Space Kobold Games and Contributors <https://github.com/space-kobold/alpha-paradox>
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
    "darkfx.json",
]
SPDX-FileCopyrightText = [
    "2017-2025 Space Wizards Federation and Contributors <https://github.com/space-wizards/space-station-14>",
    "2019-2021 Steffen Wilke and Contributors <https://github.com/steffen-wilke/darkfx>",
]
SPDX-License-Identifier = "LicenseRef-MIT-SpaceWizards AND LicenseRef-MIT-DarkFX"
