# SPDX-FileCopyrightText: 2025 Space Kobold Games and Contributors <https://github.com/space-kobold/alpha-paradox>
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
    "CLA-v1.json"
]
SPDX-FileCopyrightText = "2025 Space Kobold Games and Contributors <https://github.com/space-kobold/alpha-paradox>"
SPDX-License-Identifier = "CC0-1.0"
